# Generated by Django 5.2.3 on 2025-07-15 05:16

import cloudinary_storage.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0002_alter_profile_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100)),
                ('owner_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('notes', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('logo', models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage, upload_to='logos')),
                ('banner', models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage, upload_to='banners')),
                ('app', models.CharField(max_length=1000)),
                ('number', models.CharField(max_length=20)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('image', models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage, upload_to='product images')),
                ('currency', models.CharField(choices=[('egp', 'egp'), ('usd', 'usd'), ('eur', 'eur')])),
                ('price', models.IntegerField()),
                ('savers', models.ManyToManyField(blank=True, null=True, related_name='product_savers', to='Accounts.profile')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.store')),
            ],
        ),
    ]
