# Generated by Django 5.2.3 on 2025-07-16 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_avaialbe',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
