# Generated by Django 5.2.3 on 2025-07-16 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_is_avaialbe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_avaialbe',
            new_name='is_available',
        ),
    ]
