# Generated by Django 5.2.3 on 2025-07-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='custom_order_link',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
